jobs:
  darkube_build_test_parsahajighasemi-test_hamravesh-c23:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: registry.hamdocker.ir/parsahajighasemi/hajparsahghamravesh_test-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./Dockerfile
        --build-context . '
  darkube_deploy_test_parsahajighasemi-test_hamravesh-c23:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_test_parsahajighasemi-test_hamravesh-c23
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_TEST_PARSAHAJIGHASEMI_TEST_HAMRAVESH_C23}}
        --app-id ${{secrets.APP_ID_TEST_PARSAHAJIGHASEMI_TEST_HAMRAVESH_C23}} --image-tag
        ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
'on':
  push:
    branches:
    - main
